policy: ppo
policy_spec:
  clip_epsilon: 0.2
  entropy_coef: 0.
  critic_coef: 0.75
  gamma: 0.99
  loss_critic_type: smooth_l1
actor_net_spec:
  depth: 2
  num_cells: 16
value_net_spec:
  depth: 2
  num_cells: 64
other_spec:
  activation: relu
  gae_spec:
    gamma: 0.99
    lmbda: 0.95
    average_gae: True
  sampler:
    _target_: torchrl.data.replay_buffers.samplers.SamplerWithoutReplacement