policy: sac
policy_spec:
  num_qvalue_nets: 3
  gamma: 0.99
  delay_actor: False,
  delay_qvalue: True,
actor_net_spec:
  depth: 2
  num_cells: 32
value_net_spec:
  depth: 2
  num_cells: 64
other_spec:
  activation: relu
  alpha_lr: 0.003
  init_random_frames: 3600
  target_update_polyak: 0.005
  sampler:
    _target_: torchrl.data.replay_buffers.samplers.RandomSampler