policy: sac
policy_spec:
  num_qvalue_nets: 2
  gamma: 0.99
  delay_actor: False,
  delay_qvalue: True,
actor_net_spec:
  depth: 2
  num_cells: 8
value_net_spec:
  depth: 2
  num_cells: 32
other_spec:
  activation: relu
  alpha_lr: 0.0003
  init_random_frames: 100
  target_update_polyak: 0.01
  sampler:
    _target_: torchrl.data.replay_buffers.samplers.RandomSampler