defaults:
  - _self_
  - data: ems.yaml
  - model: sac.yaml

device:
  _target_: torch.device
  device: cpu

wandb_log: True
frames_per_batch: 5008
num_envs: 16
update_rounds: 10
batch_size: 512
buffer_size: 100000
train_iter: 50
lr: 0.005
schedule_lr: True
end_lr: 0.0005
max_grad_norm: 0.5
eval_interval: 1
eval_rollouts: 3
eval_rollout_steps: 1000
