defaults:
  - _self_
  - data: msc.yaml
  - model: sac.yaml

device:
  _target_: torch.device
  device: cpu

wandb_log: True
frames_per_batch: 120
num_envs: 4
update_rounds: ${.frames_per_batch}
batch_size: 32
buffer_size: 800000
prb: False
total_frames: 100000
actor_lr: 0.0005
critic_lr: 0.0005
schedule_lr: False
schedule_factor: 0.9998
weight_decay: 0.1
max_grad_norm: 0.5
eval_interval: 3
eval_rollouts: 20
eval_rollout_steps: 1000
test_rollouts: 100
seed: 0
