defaults:
  - _self_
  - data: ems.yaml
  - model: td3.yaml

device:
  _target_: torch.device
  device: cpu

wandb_log: True
frames_per_batch: 1200
num_envs: 2
update_rounds: 10
batch_size: 128
buffer_size: 800000
prb: False
train_iter: 100
actor_lr: 0.001
critic_lr: 0.008
schedule_lr: True
schedule_factor: 0.9998
weight_decay: 0.1
max_grad_norm: 0.5
eval_interval: 3
eval_rollouts: 50
eval_rollout_steps: 1000
seed: 0
